### ISSUE TITLE
Login page shall redirect when already logged in

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#117]
Test case:
* consider you are already logged
* in another browser tab open the login page, e.g. http://w101.metasfresh.com:8090/login?redirect=true
* the page login page is displayed => NOK, it shall redirect
* you are allowed to enter user & password and press enter/login
* you get Access Denied error because u are already logged in:

![image](https://cloud.githubusercontent.com/assets/1244701/20701796/8161baec-b61d-11e6-8209-2613f0e87566.png)

**Comment by metas-rc** [comment]
This broke again after the last release. Please, check.

**Comment by Dunkat** [comment]
fixed

**Comment by teosarca** [comment]
Hi @Dunkat 

Did a quick check on my laptop but it's still broken.

Pls check it again.

IMPORTANT for your test:
* make sure u are not logged in
* make sure you are opening the browser page: http://<host>/login?redirect=true

**Comment by damianprzygodzki** [comment]
For me both cases works like a charm. First:
-you are not logged in
-you are opening `login` or `login?redirect=true`
-the login page is open - OK
2#
-you are logged in
-you are opening `login` or `login?redirect=true`
-there is redirect to `dashboard` - OK

**Comment by teosarca** [comment]
Reproduced now:

![image](https://cloud.githubusercontent.com/assets/1244701/21174771/c00ff184-c1e7-11e6-881d-9b1f2536e761.png)

**Comment by Dunkat** [comment]
is the problem still repeating?

**Comment by teosarca** [comment]
nop. seems to be fixed.
Thanks.
