### ISSUE TITLE
Menu's first element is hidden behind on mobile

### ISSUE THREAD

**Issue by teosarca** [metasfresh/metasfresh-webui-frontend#547]
### Current behavior
* Open the frontend on mobile.
* Press on Home button
* Menu's first item (i.e. New BPartner) is hidden

![image](https://cloud.githubusercontent.com/assets/1244701/24009027/4d744728-0a7c-11e7-8719-e2101fa65d69.png)

### Expected behavior
Layout shall be fixed for mobile and the whole menu shall be visible.

**Comment by metas-lc** [comment]
IT
tested it on mobile: 
- i can see first entry in home, also "dashboard" and "crm" OK
- on chrome i can't see the last entry and on safari "browse the whole menu" is cut and i can't select it NOK

![17572082_1858138387775579_2050122288_o](https://cloud.githubusercontent.com/assets/16001666/24409149/09187e40-13d8-11e7-96a2-6342c27bf1f5.png)

![17619005_10208937223572741_1541484807_n](https://cloud.githubusercontent.com/assets/16001666/24409160/0ee47cac-13d8-11e7-9214-3b3950284be7.jpg)

**Comment by metas-rc** [comment]
It is still not working on my phone (Android 7.0 )

![metasfresh menu on android 7](https://cloud.githubusercontent.com/assets/16001442/25225875/b2890440-25cb-11e7-8644-ad6cb56752ad.png)

@metas-lc  said it works on Safari

**Comment by damianprzygodzki** [comment]
@metas-rc 
> It is still not working on my phone (Android 7.0 )
This is not a case of this issue, but i fixed that anyway, is it okay now?

**Comment by metas-rc** [comment]
The Android problem I wrote about was not solved. I created a new task for it: https://github.com/metasfresh/metasfresh-webui-frontend/issues/665

**Comment by damianprzygodzki** [comment]
@metas-rc so can we close this issue if we're creating another?
